name = "showtime"
version = "0.3.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
licences = ["Apache-2.0"]
description = "A Gleam Testing Framework"
repository = { type = "github", user = "JohnBjrk", repo = "showtime" }
# links = [{ title = "Website", href = "https://gleam.run" }]
gleam = ">= 1.0.0"
target = "erlang"

[dependencies]
gleam_stdlib = "~> 0.36"
gleam_erlang = "~> 0.24"
gleam_otp = "~> 0.10"
gleam_community_ansi = "~> 1.4"
glint = "~> 0.18.0"
gap = "~> 1.1"
snag = "~> 0.3"
simplifile = "~> 1.5"

[dev-dependencies]
gleeunit = "~> 1.0"

[javascript.deno]
allow_read = ["./"]

