name = "showtime"
version = "0.0.2"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
licences = ["Apache-2.0"]
description = "A Gleam Testing Framework"
repository = { type = "github", user = "JohnBjrk", repo = "showtime" }
# links = [{ title = "Website", href = "https://gleam.run" }]
target = "erlang"

[dependencies]
gleam_stdlib = "~> 0.26"
gleam_erlang = "~> 0.17"
gleam_otp = "~> 0.5"
gleam_community_ansi = "~> 1.1"
glint = "~> 0.10"
gap = "~> 0.1"

[dev-dependencies]
gleeunit = "~> 0.10"
